[package]
name = "forge_force_dev"
version = "1.0.0"
authors = ['yb']
# for easier debug and development. Will be immuatble.
upgrade_policy = "compatible"

[addresses]

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
