[package]
name = "forge_force_dev_v5"
version = "1.0.0"
authors = ['yb']
# for easier debug and development. Will be immuatble.
upgrade_policy = "compatible"

[addresses]

[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "eb0144a39ada521d8dee01c9dbd601853d383fb3" }

[dev-dependencies]
